CREATE TABLE users
(
 "id"         int NOT NULL,
 name       varchar(50) NOT NULL,
 email      varchar(50) NOT NULL,
 username   varchar(50) NOT NULL,
 start_date date NOT NULL,
 CONSTRAINT PK_users PRIMARY KEY ( "id" ),
 CONSTRAINT email UNIQUE ( email ),
 CONSTRAINT username UNIQUE ( username )
);
-- ************************************** store

CREATE TABLE store
(
 "id"       varchar(50) NOT NULL,
 owner    int NOT NULL,
 name     varchar(50) NOT NULL,
 location varchar(50) NOT NULL,
 CONSTRAINT PK_store PRIMARY KEY ( "id" ),
 CONSTRAINT FK_owner FOREIGN KEY ( owner ) REFERENCES users ( "id" )
);

CREATE INDEX FK_1_owner ON store
(
 owner
);

-- ************************************** products

CREATE TABLE products
(
 "id"        int NOT NULL,
 name      varchar(50) NOT NULL,
 buyer_id  int NULL,
 store_id  varchar(50) NOT NULL,
 seller_id int NOT NULL,
 sold      boolean NOT NULL,
 quantity  int NOT NULL,
 photo_id  varchar(50) NOT NULL,
 CONSTRAINT PK_products PRIMARY KEY ( "id" ),
 CONSTRAINT FK_products_users FOREIGN KEY ( seller_id ) REFERENCES users ( "id" ),
 CONSTRAINT FK_products_store FOREIGN KEY ( store_id ) REFERENCES store ( "id" )
);

CREATE INDEX FK_products_users ON products
(
 seller_id
);

CREATE INDEX FK_products_store ON products
(
 store_id
);


-- ************************************** orders

CREATE TABLE orders
(
 "id"         int NOT NULL,
 buyer_id   int NOT NULL,
 "date"       date NOT NULL,
 total_cost money NOT NULL,
 CONSTRAINT PK_orders PRIMARY KEY ( "id" ),
 CONSTRAINT FK_orders_users FOREIGN KEY ( buyer_id ) REFERENCES users ( "id" )
);

CREATE INDEX FK_orders_users ON orders
(
 buyer_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- * Generated by SqlDBM: e-commerce project, v9 by ben2.2low@gmail.com *



-- ************************************** order_products

CREATE TABLE order_products
(
 order_id   int NOT NULL,
 product_id int NOT NULL,
 CONSTRAINT FK_order_products_orders FOREIGN KEY ( order_id ) REFERENCES orders ( "id" ),
 CONSTRAINT FK_order_products_products FOREIGN KEY ( product_id ) REFERENCES products ( "id" )
);

CREATE INDEX FK_order_products_orders ON order_products
(
 order_id
);

CREATE INDEX FK_order_products_products ON order_products
(
 product_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- * Generated by SqlDBM: e-commerce project, v9 by ben2.2low@gmail.com *



-- ************************************** sizes

CREATE TABLE sizes
(
 "id"          int NOT NULL,
 description varchar(50) NOT NULL,
 CONSTRAINT PK_sizes PRIMARY KEY ( "id" )
);







-- ************************* SqlDBM: PostgreSQL *************************
-- * Generated by SqlDBM: e-commerce project, v9 by ben2.2low@gmail.com *



-- ************************************** item_size

CREATE TABLE item_size
(
 product_id  int NOT NULL,
 size_id     int NOT NULL,
 description varchar(100) NOT NULL,
 price       money NOT NULL,
 colour      varchar(50) NOT NULL,
 type        varchar(50) NOT NULL,
 "condition"   varchar(50) NOT NULL,
 CONSTRAINT FK_item_size_products FOREIGN KEY ( product_id ) REFERENCES products ( "id" ),
 CONSTRAINT FK_item_size_sizes FOREIGN KEY ( size_id ) REFERENCES sizes ( "id" )
);

CREATE INDEX FK_item_size_products ON item_size
(
 product_id
);

CREATE INDEX FK_item_size_sizes ON item_size
(
 size_id
);

